# Generated by Django 4.1.5 on 2023-02-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
